# -*- coding: utf-8 -*-
"""create_folds.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P-Pf_r3KRi2Wzvt9oBxRGLgUJiNtuvAZ
"""

# https://github.com/trent-b/iterative-stratification
# https://www.kaggle.com/c/tweet-sentiment-extraction/discussion/142404
import pandas as pd
from iterstrat.ml_stratifiers import MultilabelStratifiedKFold

if __name__ == "__main__":
  df = pd.read_csv("./input/train.csv")
  print(df.head())
  df.loc[:, 'kfold'] = -1

  # Return a random sample of items from an axis of object.
  # You can use random_state for reproducibility.
  df = df.sample(frac=1).reset_index(drop=True)

  # Return a Numpy representation of the DataFrame.
  X = df.image_id.values
  y = df[["grapheme_root", "vowel_diacritic", "consonant_diacritic"]].values

  mskf = MultilabelStratifiedKFold(n_splits=5)

  for fold, (trn_, val_) in enumerate(mskf.split(X,y)):
      print("TRAIN: ", trn_, "VAL: ", val_)
      df.loc[val_, "kfold"] = fold

  print(df.kfold.value_counts())
  df.to_csv("./input/train_folds.csv", index=False)