# -*- coding: utf-8 -*-
"""model_dispatcher.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/190EFGCUJLXXNOiLWfn_RMHOwmvtIQjvs
"""

import models

MODEL_DISPATCHER = {
    'resnet34' : models.ResNet34 
}